import {
  Activity, AlertTriangle, BadgeCheck, Bell, Briefcase, Calendar, CalendarCheck, Camera,
  Check, CheckCircle, CheckCircle2, ChevronDown, ChevronLeft, ChevronRight, ChevronUp, Circle,
  Clock, Copy, Droplets, Download, Eye, EyeOff, File, FileText, FileUp, Film, Flag,
  FlaskConical, Gauge, Gift, Globe, Hash, Heart, Home, Image, Info, KeyRound, Languages,
  LayoutDashboard, Link, ListChecks, Mail, MapPin, MessageCircle, MessageSquare, Moon, MoreHorizontal,
  Paperclip, Pause, Pencil, Phone, PhoneCall, PhoneOff, Pill, PlayCircle, Plane, Plus,
  Repeat, Save, Scissors, Search, Send, Settings, Share2, Shield, ShieldCheck, Shirt,
  SkipForward, Sparkles, Star, Sun, Trash2, Trophy, Upload, User, UserPlus, Users, Utensils,
  Video as VideoIcon, Volume2, X, XCircle, Zap,
} from 'lucide-vue-next';

/**
 * Whitelist Lucide ikon používaných v appce (dle ADMIN-SPEC Appendix B).
 * Klíč = název, který admin ukládá jako `icon` stringem. Hodnota = Vue komponenta.
 */
export const ICON_MAP: Record<string, unknown> = {
  activity: Activity,
  'alert-triangle': AlertTriangle,
  'badge-check': BadgeCheck,
  bell: Bell,
  briefcase: Briefcase,
  calendar: Calendar,
  'calendar-check': CalendarCheck,
  camera: Camera,
  check: Check,
  'check-circle': CheckCircle,
  'check-circle-2': CheckCircle2,
  'chevron-down': ChevronDown,
  'chevron-left': ChevronLeft,
  'chevron-right': ChevronRight,
  'chevron-up': ChevronUp,
  circle: Circle,
  clock: Clock,
  copy: Copy,
  download: Download,
  droplets: Droplets,
  eye: Eye,
  'eye-off': EyeOff,
  file: File,
  'file-text': FileText,
  'file-up': FileUp,
  film: Film,
  flag: Flag,
  'flask-conical': FlaskConical,
  gauge: Gauge,
  gift: Gift,
  globe: Globe,
  hash: Hash,
  heart: Heart,
  home: Home,
  image: Image,
  info: Info,
  'key-round': KeyRound,
  languages: Languages,
  'layout-dashboard': LayoutDashboard,
  link: Link,
  'list-checks': ListChecks,
  mail: Mail,
  'map-pin': MapPin,
  'message-circle': MessageCircle,
  'message-square': MessageSquare,
  moon: Moon,
  'more-horizontal': MoreHorizontal,
  paperclip: Paperclip,
  pause: Pause,
  pencil: Pencil,
  phone: Phone,
  'phone-call': PhoneCall,
  'phone-off': PhoneOff,
  pill: Pill,
  'play-circle': PlayCircle,
  plane: Plane,
  plus: Plus,
  repeat: Repeat,
  save: Save,
  scissors: Scissors,
  search: Search,
  send: Send,
  settings: Settings,
  'share-2': Share2,
  shield: Shield,
  'shield-check': ShieldCheck,
  shirt: Shirt,
  'skip-forward': SkipForward,
  sparkles: Sparkles,
  star: Star,
  sun: Sun,
  'trash-2': Trash2,
  trophy: Trophy,
  upload: Upload,
  user: User,
  'user-plus': UserPlus,
  users: Users,
  utensils: Utensils,
  video: VideoIcon,
  'volume-2': Volume2,
  x: X,
  'x-circle': XCircle,
  zap: Zap,
};

export function resolveIcon(name: string | undefined): unknown {
  if (!name) return ICON_MAP['circle'];
  return ICON_MAP[name] ?? ICON_MAP['circle'];
}

export const COMPONENT_TYPE_ICONS: Record<string, string> = {
  info: 'info',
  instrukce: 'check',
  varovani: 'alert-triangle',
  nebezpeci: 'x-circle',
  uspech: 'check-circle',
};

/** Icons whitelisted for the component icon picker (Appendix B). */
export const PICKER_ICONS: string[] = [
  'droplets', 'pill', 'moon', 'sun', 'camera', 'flask-conical', 'scissors', 'activity',
  'utensils', 'shirt', 'briefcase', 'flag', 'zap', 'map-pin', 'plane', 'home',
  'calendar-check', 'trophy', 'sparkles', 'check', 'check-circle', 'clock',
  'alert-triangle', 'info', 'x-circle', 'shield-check', 'list-checks', 'play-circle',
  'user', 'bell', 'message-circle', 'file-text', 'volume-2',
];
